export const siteConfig = {
  name: 'Berglunds Byggtjänst Östersund',
  description: 'Kvalitetsbyggnation i Östersund och Jämtland',
  url: 'https://berglundsbyggtjanst.se',
  email: 'infoberglundsbyggtjanstosd@gmail.com',
  phone: '070 321 88 27',
  address: 'Namn 110, 832 93 Frösön',
  social: {
    facebook: 'https://www.facebook.com/people/Berglunds-Byggtjänst-Östersund/61554649092027',
    instagram: 'https://www.instagram.com/berglundsbyggtjanstosd',
  },
  navigation: [
    { name: 'Hem', href: '/' },
    { name: 'Tjänster', href: '/tjanster/' },
    { name: 'Referenser', href: '/referenser/' },
    { name: 'Om oss', href: '/om-oss/' },
    { name: 'ROT-avdrag', href: '/rot-avdrag/' },
  ],
  cta: {
    text: 'Få en offert',
    href: '/offert/',
  },
}

export const services = [
  {
    id: 'takbyten',
    slug: 'takbyten',
    title: 'Takbyten & takarbeten',
    shortDescription: 'Ett tätt och tryggt tak över huvudet',
    description: 'Taket är ditt hems viktigaste skydd mot väder och vind. Vi utför kompletta takbyten, takomläggningar och takreparationer med fokus på långsiktig hållbarhet.',
    imageUrl: '/images/hero/hero-main.jpg',
    features: [
      'Kompletta takbyten',
      'Takreparationer',
      'Läckagesökning',
      'Byte av takpannor/plåt',
      'Stuprör och hängrännor',
      'Installation av takfönster',
      'Ventilationslösningar',
    ],
    icon: 'Home',
    hasRot: true,
  },
  {
    id: 'badrumsrenovering',
    slug: 'badrumsrenovering',
    title: 'Badrumsrenoveringar',
    shortDescription: 'Ditt drömbadrum förtjänar experter',
    description: 'Ett badrum är mer än kakel och kran – det är kvalitetstid varje dag. Vi renoverar kompletta badrum med professionell VVS, vattentät tätskiktning och moderna lösningar.',
    imageUrl: 'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=1920&q=80',
    features: [
      'Design och materialval',
      'Rivning',
      'VVS-arbeten',
      'Tätskikt',
      'Kakel och klinker',
      'Snickeriarbeten',
      'Slutbesiktning',
    ],
    icon: 'Bath',
    hasRot: true,
  },
  {
    id: 'nybyggnation',
    slug: 'nybyggnation',
    title: 'Nybyggnation & tillbyggnader',
    shortDescription: 'Behöver du mer plats? Vi bygger din dröm',
    description: 'Vi hanterar hela processen från ritningar och bygglov till färdig nyckel. Oavsett om du vill bygga nytt hus, göra en tillbyggnad eller bygga ut altanen.',
    imageUrl: 'https://images.unsplash.com/photo-1541888946425-d81bb19240f5?w=1920&q=80',
    features: [
      'Planering',
      'Bygglovsansökan',
      'Grundläggning',
      'Stomme',
      'Tak',
      'Fasad',
      'Invändig snickeri',
    ],
    icon: 'Building2',
    hasRot: true,
  },
  {
    id: 'ombyggnation',
    slug: 'ombyggnation',
    title: 'Ombyggnation & renovering',
    shortDescription: 'Förnya ditt hem – bevara själen',
    description: 'Varje hem har sin historia. Vi är experter på att modernisera och förbättra utan att förlora karaktären. Från köksbyte till helhetslösningar.',
    imageUrl: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=1920&q=80',
    features: [
      'Köksrenovering',
      'Trapprenovering',
      'Golvslipning',
      'Fönsterbyte',
      'Fasadförbättring',
      'Helhetslösningar',
    ],
    icon: 'Hammer',
    hasRot: true,
  },
  {
    id: 'snickeri',
    slug: 'snickeriarbeten',
    title: 'Snickeriarbeten & inredning',
    shortDescription: 'Specialanpassad inredning för ditt hem',
    description: 'Trappor, inbyggda garderober, förvaringslösningar eller specialritade möbler – vi skapar skräddarsydd inredning som passar perfekt i ditt hem.',
    imageUrl: 'https://images.unsplash.com/photo-1502005229762-cf1b2da7c5d6?w=1920&q=80',
    features: [
      'Trappor',
      'Inbyggda garderober',
      'Förvaringslösningar',
      'Specialritade möbler',
      'Köksinredning',
      'Listverk',
    ],
    icon: 'Wood',
    hasRot: true,
  },
]

export const values = [
  {
    title: 'Ärlig kommunikation',
    description: 'Inga dolda kostnader eller överraskningar. Vi säger som det är.',
    icon: 'MessageCircle',
  },
  {
    title: 'Respekt för ditt hem',
    description: 'Vi städar efter oss och är varsamma med din egendom.',
    icon: 'Heart',
  },
  {
    title: 'Hållbar kvalitet',
    description: 'Vi bygger för att hålla i generationer, inte bara idag.',
    icon: 'Shield',
  },
  {
    title: 'Personligt ansvar',
    description: 'Du når alltid samma person som känner ditt projekt.',
    icon: 'User',
  },
]
